# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQqN64MMdGf20Shg4PbA5rqivrMIIuQL
"""

import gradio as gr
import matplotlib.pyplot as plt

from predict import PhishingPredictor
from intent_detection import IntentDetector
from url_analysis import URLAnalyzer
from sender_analysis import SenderAnalyzer
from risk_score import RiskScorer
from graph_analysis import GraphAnalyzer


# ----------------------------
# Load Modules
# ----------------------------

predictor = PhishingPredictor(
    model_path="phishing_model.pkl",
    vectorizer_path="vectorizer.pkl"
)

intent_detector = IntentDetector()

url_analyzer = URLAnalyzer()

sender_analyzer = SenderAnalyzer()

risk_scorer = RiskScorer()

graph_analyzer = GraphAnalyzer()


# ----------------------------
# Main Function
# ----------------------------

def analyze(sender, subject, body):

    email = subject + "\n\n" + body

    ml_result = predictor.predict(email)

    intent_result = intent_detector.detect(email)

    url_result = url_analyzer.analyze(email)

    sender_result = sender_analyzer.analyze(sender)

    risk_result = risk_scorer.calculate(

        prediction_result=ml_result,

        intent_result=intent_result,

        url_result=url_result,

        sender_result=sender_result

    )

    # Graph

    graph = graph_analyzer.draw_graph(

        sender,

        ml_result["prediction"]

    )

    output = f"""

📧 SecureMail AI Report

-----------------------------------------

Prediction :
{ml_result['prediction']}

Confidence :
{ml_result['confidence']} %

-----------------------------------------

Intent :
{intent_result['intent']}

-----------------------------------------

Sender Reputation :
{sender_result['reputation']}

Domain :
{sender_result['domain']}

-----------------------------------------

URL Risk :
{url_result['risk']}

-----------------------------------------

Risk Score :
{risk_result['risk_score']} /100

Risk Level :
{risk_result['risk_level']}

-----------------------------------------

Reasons

"""

    for r in risk_result["reasons"]:

        output += f"\n• {r}"

    output += f"""

-----------------------------------------

Recommendation

{risk_result['recommendation']}

"""

    return output, graph


# ----------------------------
# Gradio UI
# ----------------------------

demo = gr.Interface(

    fn=analyze,

    inputs=[

        gr.Textbox(

            label="Sender Email"

        ),

        gr.Textbox(

            label="Subject"

        ),

        gr.Textbox(

            label="Email Body",

            lines=12

        )

    ],

    outputs=[

        gr.Textbox(

            label="SecureMail AI Result",

            lines=30

        ),

        gr.Plot(

            label="Sender Relationship Graph"

        )

    ],

    title="🛡 SecureMail AI",

    description="""
Intelligent Phishing Detection Using Email Intent
and Behavioral Analysis
"""

)

demo.launch(share=True)