# -*- coding: utf-8 -*-
"""graph_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQqN64MMdGf20Shg4PbA5rqivrMIIuQL
"""

"""
graph_analysis.py
-----------------------------------------
SecureMail AI
Sender Relationship Graph
"""

import networkx as nx
import matplotlib.pyplot as plt


class GraphAnalyzer:

    def __init__(self):

        self.graph = nx.Graph()

    def create_graph(self, sender, prediction):

        self.graph.clear()

        sender = sender.strip()

        email_node = "Current Email"

        self.graph.add_node(
            sender,
            color="red" if prediction == "Phishing" else "green"
        )

        self.graph.add_node(
            email_node,
            color="skyblue"
        )

        self.graph.add_edge(sender, email_node)

        return self.graph

    def draw_graph(self, sender, prediction):

        self.create_graph(sender, prediction)

        colors = []

        for node in self.graph.nodes():

            if node == "Current Email":

                colors.append("skyblue")

            elif prediction == "Phishing":

                colors.append("red")

            else:

                colors.append("green")

        plt.figure(figsize=(6,4))

        pos = nx.spring_layout(self.graph, seed=42)

        nx.draw_networkx(

            self.graph,

            pos,

            node_color=colors,

            node_size=2200,

            font_size=10,

            font_weight="bold",

            edge_color="gray"

        )

        plt.title("Sender Relationship Graph")

        plt.axis("off")

        plt.tight_layout()

        return plt


if __name__ == "__main__":

    analyzer = GraphAnalyzer()

    analyzer.draw_graph(

        "security@paypal-login.xyz",

        "Phishing"

    )

    plt.show()