# -*- coding: utf-8 -*-
"""intent_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQqN64MMdGf20Shg4PbA5rqivrMIIuQL
"""

"""
intent_detection.py
SecureMail AI

Detects the likely intent of an email using keyword analysis.
"""


class IntentDetector:

    def __init__(self):

        self.intent_rules = {

            "Credential Theft": [
                "password",
                "login",
                "verify",
                "verification",
                "username",
                "credential",
                "confirm account",
                "reset password"
            ],

            "Financial Fraud": [
                "bank",
                "payment",
                "credit card",
                "debit card",
                "transaction",
                "invoice",
                "refund",
                "wire transfer"
            ],

            "Malware Delivery": [
                "attachment",
                "download",
                "install",
                "document",
                "zip",
                "exe",
                "macro"
            ],

            "Account Verification Scam": [
                "account suspended",
                "security alert",
                "otp",
                "verify identity",
                "locked account"
            ],

            "Social Engineering": [
                "urgent",
                "immediately",
                "act now",
                "within 24 hours",
                "limited time",
                "confidential"
            ],

            "Normal Communication": [
                "meeting",
                "schedule",
                "discussion",
                "project",
                "thank you",
                "regards"
            ]
        }

    def detect(self, text):

        text = text.lower()

        best_intent = "General Communication"

        score = 0

        matched = []

        for intent, keywords in self.intent_rules.items():

            count = 0

            for word in keywords:

                if word in text:
                    count += 1
                    matched.append(word)

            if count > score:
                score = count
                best_intent = intent

        return {

            "intent": best_intent,

            "score": min(score * 15, 100),

            "matched_keywords": list(set(matched))
        }


if __name__ == "__main__":

    detector = IntentDetector()

    sample = """
    Dear Customer,

    Your account has been suspended.

    Verify your password immediately.

    """

    print(detector.detect(sample))