# -*- coding: utf-8 -*-
"""predict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQqN64MMdGf20Shg4PbA5rqivrMIIuQL
"""

"""
predict.py
SecureMail AI

Loads the trained ML model and vectorizer, then predicts
whether an email is phishing or legitimate.
"""

import joblib
import os


class PhishingPredictor:
    def __init__(
        self,
        model_path="phishing_model.pkl",
        vectorizer_path="vectorizer.pkl"
    ):

        if not os.path.exists(model_path):
            raise FileNotFoundError(
                f"Model not found: {model_path}"
            )

        if not os.path.exists(vectorizer_path):
            raise FileNotFoundError(
                f"Vectorizer not found: {vectorizer_path}"
            )

        self.model = joblib.load(model_path)
        self.vectorizer = joblib.load(vectorizer_path)

    def preprocess(self, text):
        if text is None:
            return ""
        return str(text).strip()

    def predict(self, email_text):

        email_text = self.preprocess(email_text)

        X = self.vectorizer.transform([email_text])

        prediction = self.model.predict(X)[0]

        if hasattr(self.model, "predict_proba"):
            confidence = max(
                self.model.predict_proba(X)[0]
            ) * 100
        else:
            confidence = 100.0

        label = (
            "Phishing"
            if prediction == 1
            else "Legitimate"
        )

        return {
            "prediction": label,
            "confidence": round(confidence, 2)
        }


if __name__ == "__main__":

    sample_email = """
    Dear Customer,

    Your account has been suspended.

    Click below to verify immediately.

    http://paypal-login-security.xyz
    """

    predictor = PhishingPredictor()

    result = predictor.predict(sample_email)

    print(result)