# -*- coding: utf-8 -*-
"""risk_score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQqN64MMdGf20Shg4PbA5rqivrMIIuQL
"""

"""
risk_score.py
-----------------------------------------
SecureMail AI
Final Risk Score Generator
"""

class RiskScorer:

    def __init__(self):

        self.high_risk_intents = [

            "Credential Theft",

            "Financial Fraud",

            "Malware Delivery",

            "Account Verification Scam",

            "Social Engineering"

        ]

    def calculate(

        self,

        prediction_result,

        intent_result,

        url_result,

        sender_result

    ):

        score = 0

        reasons = []

        prediction = prediction_result["prediction"]

        confidence = prediction_result["confidence"]

        # --------------------------
        # ML Prediction
        # --------------------------

        if prediction == "Phishing":

            score += 40

            reasons.append(

                f"ML model detected phishing ({confidence:.2f}% confidence)."

            )

        else:

            score += 5

        # --------------------------
        # Confidence
        # --------------------------

        if confidence >= 95:

            score += 15

        elif confidence >= 85:

            score += 10

        elif confidence >= 70:

            score += 5

        # --------------------------
        # Intent
        # --------------------------

        if intent_result["intent"] in self.high_risk_intents:

            score += intent_result["score"]

            reasons.append(

                f"Suspicious intent detected: {intent_result['intent']}."

            )

        # --------------------------
        # URL
        # --------------------------

        score += int(url_result["score"] * 0.30)

        reasons.extend(url_result["reasons"])

        # --------------------------
        # Sender
        # --------------------------

        score += int(sender_result["score"] * 0.20)

        reasons.extend(sender_result["reasons"])

        # --------------------------
        # Normalize
        # --------------------------

        if score > 100:

            score = 100

        # --------------------------
        # Risk Level
        # --------------------------

        if score >= 80:

            level = "HIGH"

            recommendation = (

                "Do NOT click links, download attachments "

                "or provide credentials."

            )

        elif score >= 50:

            level = "MEDIUM"

            recommendation = (

                "Verify the sender and all URLs before proceeding."

            )

        else:

            level = "LOW"

            recommendation = (

                "Email appears safe based on current analysis."

            )

        return {

            "risk_score": score,

            "risk_level": level,

            "recommendation": recommendation,

            "reasons": list(set(reasons))

        }


if __name__ == "__main__":

    scorer = RiskScorer()

    result = scorer.calculate(

        prediction_result={

            "prediction":"Phishing",

            "confidence":97.6

        },

        intent_result={

            "intent":"Credential Theft",

            "score":30

        },

        url_result={

            "score":80,

            "reasons":["Suspicious URL detected."]

        },

        sender_result={

            "score":60,

            "reasons":["Unknown sender."]

        }

    )

    print(result)