# -*- coding: utf-8 -*-
"""sender_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQqN64MMdGf20Shg4PbA5rqivrMIIuQL
"""

"""
sender_analysis.py
-----------------------------------------
SecureMail AI
Sender Reputation Analysis Module
"""

import re


class SenderAnalyzer:

    def __init__(self):

        self.trusted_domains = [

            "gmail.com",
            "outlook.com",
            "hotmail.com",
            "yahoo.com",

            "amazon.com",
            "amazon.in",

            "paypal.com",

            "microsoft.com",

            "google.com",

            "apple.com",

            "linkedin.com"
        ]

        self.suspicious_domains = [

            ".xyz",
            ".top",
            ".club",
            ".online",
            ".tk",
            ".cf",
            ".gq",
            ".ml",
            ".ru"

        ]

    def analyze(self, sender_email):

        sender_email = sender_email.strip().lower()

        score = 0

        reasons = []

        reputation = "Trusted"

        # ------------------------------
        # Validate email
        # ------------------------------

        if not re.match(r"[^@]+@[^@]+\.[^@]+", sender_email):

            return {

                "reputation": "Invalid",

                "score": 100,

                "domain": "Unknown",

                "reasons": [
                    "Invalid sender email address."
                ]
            }

        domain = sender_email.split("@")[1]

        # ------------------------------
        # Trusted domain
        # ------------------------------

        if domain in self.trusted_domains:

            reputation = "Trusted"

        else:

            reputation = "Unknown"

            score += 20

            reasons.append(
                "Unknown sender domain."
            )

        # ------------------------------
        # Suspicious TLD
        # ------------------------------

        for tld in self.suspicious_domains:

            if domain.endswith(tld):

                score += 30

                reputation = "Suspicious"

                reasons.append(
                    "Suspicious top-level domain."
                )

        # ------------------------------
        # Numeric characters
        # ------------------------------

        if any(ch.isdigit() for ch in domain):

            score += 10

            reasons.append(
                "Numeric characters in domain."
            )

        # ------------------------------
        # Hyphenated domains
        # ------------------------------

        if "-" in domain:

            score += 10

            reasons.append(
                "Hyphenated domain."
            )

        # ------------------------------
        # Long domain
        # ------------------------------

        if len(domain) > 25:

            score += 10

            reasons.append(
                "Unusually long domain."
            )

        score = min(score, 100)

        if score >= 70:

            reputation = "Highly Suspicious"

        elif score >= 40:

            reputation = "Suspicious"

        elif score >= 20:

            reputation = "Unknown"

        else:

            reputation = "Trusted"

        return {

            "domain": domain,

            "reputation": reputation,

            "score": score,

            "reasons": list(set(reasons))
        }


if __name__ == "__main__":

    analyzer = SenderAnalyzer()

    print(
        analyzer.analyze(
            "security-paypal@paypal-login-security.xyz"
        )
    )