# -*- coding: utf-8 -*-
"""url_analysi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yQqN64MMdGf20Shg4PbA5rqivrMIIuQL
"""

"""
url_analysis.py
-----------------------------------------
SecureMail AI
URL and Domain Analysis Module
"""

import re
from urllib.parse import urlparse
import tldextract


class URLAnalyzer:

    def __init__(self):

        self.shorteners = [
            "bit.ly",
            "tinyurl.com",
            "goo.gl",
            "ow.ly",
            "is.gd",
            "buff.ly",
            "t.co",
            "cutt.ly"
        ]

        self.suspicious_tlds = [
            ".xyz",
            ".top",
            ".club",
            ".online",
            ".tk",
            ".cf",
            ".gq",
            ".ml",
            ".ru"
        ]

        self.suspicious_keywords = [
            "login",
            "verify",
            "password",
            "secure",
            "signin",
            "account",
            "update",
            "confirm",
            "bank"
        ]

    def extract_urls(self, text):

        pattern = r'https?://[^\s]+|www\.[^\s]+'

        return re.findall(pattern, text)

    def analyze(self, text):

        urls = self.extract_urls(text)

        score = 0

        reasons = []

        details = []

        if len(urls) == 0:

            return {

                "urls": [],

                "score": 0,

                "risk": "Low",

                "reasons": ["No URLs detected."]
            }

        for url in urls:

            parsed = urlparse(url)

            domain = parsed.netloc.lower()

            info = {

                "url": url,

                "domain": domain
            }

            # HTTP

            if url.startswith("http://"):

                score += 20

                reasons.append(
                    "Uses insecure HTTP connection."
                )

            # URL Shortener

            if any(short in domain for short in self.shorteners):

                score += 20

                reasons.append(
                    "Shortened URL detected."
                )

            # Suspicious TLD

            if any(domain.endswith(tld) for tld in self.suspicious_tlds):

                score += 25

                reasons.append(
                    "Suspicious top-level domain."
                )

            # Login Keywords

            if any(word in url.lower() for word in self.suspicious_keywords):

                score += 15

                reasons.append(
                    "Sensitive keywords found in URL."
                )

            # IP Address URL

            if re.search(r"\d+\.\d+\.\d+\.\d+", domain):

                score += 30

                reasons.append(
                    "IP address used instead of domain."
                )

            extracted = tldextract.extract(domain)

            info["registered_domain"] = (
                extracted.domain +
                "." +
                extracted.suffix
            )

            details.append(info)

        score = min(score, 100)

        if score >= 70:

            risk = "High"

        elif score >= 40:

            risk = "Medium"

        else:

            risk = "Low"

        return {

            "urls": details,

            "score": score,

            "risk": risk,

            "reasons": list(set(reasons))
        }


if __name__ == "__main__":

    sample = """
    Dear Customer,

    Verify your account immediately.

    http://paypal-security-login.xyz
    """

    analyzer = URLAnalyzer()

    result = analyzer.analyze(sample)

    print(result)